#!/usr/bin/env ruby

command = ARGV.first
if command == "app_key"
  require 'digest/sha1'
  puts Digest::SHA1.hexdigest((0...32).map { ('A'..'z').to_a[rand(52)] }.join)
else
  puts <<-S
Duo API helper

Commands:
\tapp_key\t\tGenerates a token to use for app_key in DuoApi configuration
S
end
